#
# -- 1. SQL script to create table
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS CONFIG;
CREATE TABLE CONFIG (
	CONFIG_ID VARCHAR(32) NOT NULL ,
 	CONFIG_NAME VARCHAR(128) NOT NULL ,
 	PRIMARY KEY (CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 DEFAULT COLLATE=UTF8MB4_BIN;

DROP TABLE IF EXISTS CONF_CP;
CREATE TABLE CONF_CP (
  CONFIG_ID varchar(32) COLLATE utf8mb4_bin NOT NULL ,
  CP_ID varchar(32) COLLATE utf8mb4_bin NOT NULL ,
  DISPLAY_NAME varchar(128) COLLATE utf8mb4_bin NOT NULL ,
  PRIMARY KEY (CP_ID),
  CONSTRAINT ACPS_CONF_ID FOREIGN KEY (CONFIG_ID) REFERENCES CONFIG (CONFIG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

DROP TABLE IF EXISTS CONF_CP_CON;
CREATE TABLE CONF_CP_CON (
  CP_ID varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL ,
  ID varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL ,
  ENABLED varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT 'Y' ,
  PRIMARY KEY (ID),
  CONSTRAINT ACCPC_C_P_ID FOREIGN KEY (CP_ID) REFERENCES CONF_CP (CP_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
SET FOREIGN_KEY_CHECKS=1;

-- 2. Add test data
DELETE FROM CONF_CP_CON;
DELETE FROM CONF_CP;
DELETE FROM CONFIG;
INSERT INTO CONFIG(CONFIG_ID, CONFIG_NAME) VALUES ('config_1', 'config_1');
INSERT INTO CONF_CP(CONFIG_ID, CP_ID, DISPLAY_NAME) VALUES ('config_1', 'cp_id', 'cp_id');
INSERT INTO CONF_CP_CON(CP_ID, ID, ENABLED) VALUES ('cp_id', 'confCpCon', 'Y');
SELECT * FROM CONFIG;
SELECT * FROM CONF_CP;
SELECT * FROM CONF_CP_CON;